
name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  release-qgis-repo:
    name: Deploy to QGIS plugin repository
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci==2.0.1

      - name: Deploy to QGIS plugin repository
        env:
          OSGEO_USERNAME: ${{ secrets.OSGEO_USERNAME }}
          OSGEO_PASSWORD: ${{ secrets.OSGEO_PASSWORD }}
        run: qgis-plugin-ci release --osgeo-username "$OSGEO_USERNAME" --osgeo-password "$OSGEO_PASSWORD" "${GITHUB_REF##*/v}"


  release-pypi:
    name: Release to Pypi
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Inject version name
      run: sed -i "s/dev/${GITHUB_REF##*/v}/" qdmtk/version.py

    - name: Install pypa/build
      run: pip install build

    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --outdir dist/

    - name: Publish distribution
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
